resilience4j:
  circuitbreaker:
      instances:
        trialDB:
          eventConsumerBufferSize: 10
          minimumNumberOfCalls: 5
          slidingWindowSize: 20
          ringBufferSizeInClosedState: 20
          slidingWindowType: COUNT_BASED
          failureRateThreshold: 50
          waitDurationInOpenState: 90000
          permittedNumberOfCallsInHalfOpenState: 10
          ringBufferSizeInHalfOpenState: 20
          registerHealthIndicator: true
  retry:
    instances:
      trialRetry:
        maxRetryAttempts: 2
        waitDuration: 3s
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}


spring:
  application:
    name: circuit-breaker-trial
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true